# Generated by Django 6.0 on 2025-12-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0002_alter_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_no', models.CharField(blank=True, default='', max_length=12)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('C', 'Case'), ('W', 'Weight')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='company_app.company')),
            ],
            options={
                'ordering': ['company', 'item_no'],
                'indexes': [models.Index(fields=['company', 'active'], name='product_app_company_6ca516_idx'), models.Index(fields=['item_no'], name='product_app_item_no_75a563_idx')],
                'unique_together': {('company', 'item_no')},
            },
        ),
    ]
