# Generated by Django 6.0 on 2025-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_app", "0005_company_is_active"),
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("company", "item_no"), ("company", "name")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_app_name_2fec2f_idx"),
        ),
    ]
