# Generated by Django 6.0 on 2025-12-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_app", "0005_company_is_active"),
        ("product_app", "0003_update_unique_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["company", "item_no", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_app_item_no_75a563_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_app_name_2fec2f_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "item_no"], name="product_app_company_817d80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "name"], name="product_app_company_30ac34_idx"
            ),
        ),
    ]
