# Generated by Django 6.0 on 2025-12-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_alter_product_unique_together_and_more'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_orders',
            field=models.ManyToManyField(related_name='product_orders', through='order_app.ProductOrder', to='product_app.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
