# Generated by Django 6.0 on 2025-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
