# Generated by Django 6.0 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
