# Generated by Django 6.0 on 2025-12-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_app", "0003_alter_company_options_company_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
