# Generated by Django 6.0 on 2025-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_app", "0004_alter_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive companies will not appear in order creation.",
            ),
        ),
    ]
