# Generated by Django 6.0 on 2025-12-10 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_user_display_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_signature",
            field=models.TextField(
                blank=True,
                help_text="Your email signature. Will be inserted where %signature% appears in templates.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user account is active. Unselect to disable the account.",
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name to identify this template", max_length=100
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        default="Order Request for %company_name%",
                        help_text="Email subject. Variables: %company_name%, %order_id%, %order_date%",
                        max_length=255,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Email body. Use variables like %order_items%, %signature%, etc."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this template by default when composing emails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
